const catchError = error => Promise.reject(error);

export default catchError;

